repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
        - id: add-trailing-comma
          args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
        - id: black
          language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
        - id: flake8
          args: [--config=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        language_version: python3.10
        args: [--config-file=pyproject.toml]
